# 이것은 TOML 형식의 설정파일입니다.
title = "BSE VAT Configuration"

[owner]
name = "BSE Cosulting Co.,Ltd"

# VAT Web Server 관련 설정.
[database]
server = "127.0.0.1"
ports = 3000
enabled = true

# 연결할 Database 연결정보.
[servers]

  #NAV MSSQL 서버 정보.
	[servers.nav]
	ip = "nav.bsecamp.net"
	port = 1433
	instance = "VAT"
	company = "KIMEX"
	vat_table = "B_KoreanVAT Entry"

  #VAT 정보를 위한 Mongo Database 정보.
	[servers.mongo]
	ip = "127.0.0.1"
	port = 27017
	instance = "BSEVAT"