# V105-1 매입처별 계산서 합계표
title = "VAT105-1"
[V105-1]
# 매입처별 계산서 합계표의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String","true"],             #Main Key. << 모든 정의에 들어 있어야 함. 세번째 항목은 Key 값 유무.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

   ["TOTAL_PURCH_CNT","Number"],             #매입세금계산서 총합계-매입처수 합계
   ["TOTAL_PURCH_QTY","Number"],             #매입세금계산서 총합계-매수 합계
   ["TOTAL_PURCH_ACT_AMT","Number"],         #매입세금계산서 총합계-매입금액 합계


   ["ELEC_BUS_PURCH_CNT","Number"],          #매입세금계산서 -전자세금계산서발급분-발급분-매입처수
   ["ELEC_BUS_PURCH_QTY","Number"],          #매입세금계산서 -전자세금계산서발급분-발급분-매수
   ["ELEC_BUS_PURCH_ACT_AMT","Number"],      #매입세금계산서 -전자세금계산서발급분-발급분-매입금액


   ["ELEC_PSN_PURCH_CNT","Number"],          #매입세금계산서 -전자세금계산서발급분 외-발급분-매입처수
   ["ELEC_PSN_PURCH_QTY","Number"],          #매입세금계산서 -전자세금계산서발급분 외-발급분-매수
   ["ELEC_PSN_PURCH_ACT_AMT","Number"],      #매입세금계산서 -전자세금계산서발급분 외-발급분-매입금액

   [
       ["NON_ELEC_NO","Number"],             #전자세금계산서외 발급분에 대한 매입처별 명세-일련번호
       ["NON_ELEC_BUS_NO","String"],         #전자세금계산서외 발급분에 대한 매입처별 명세-사업자등록번호
       ["NON_ELEC_BUS_NAME","String"],       #전자세금계산서외 발급분에 대한 매입처별 명세-상호(법인명)
       ["NON_ELEC_QTY","Number"],            #전자세금계산서외 발급분에 대한 매입처별 명세-매수
       ["NON_ELEC_ACT_AMT","Number"],        #전자세금계산서외 발급분에 대한 매입처별 명세-매입금액

       ["ETC","String"]                      #전자세금계산서외 발급분에 대한 매입처별 명세-비고
   ]


]

# 화면상의 계산 식을 위한 공간 / 자동화 하기 위해 고민이 필요함.
calc = [
["TOTAL_AMOUNT","(CARD_TOTAL_AMOUNT+CASH_TOTAL_AMOUNT-XXX)/YYY*ZZZ"]
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V105-1 (매입처별 계산서 합계표)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Pay_Bill CorpIndv Type",
"BSE_ETAX Complete issue",
"BSE_Editable Tot Total Amount",
"BSE_Editable Tot Actual Amount",
"BSE_VAT Registration No_",
"BSE_VAT Name"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V105-1.Condition]]
key = "BSE_VAT Type"    #매입/매출 구분
value = "0"             #매입
value_type = "Integer"

[[V105-1.Condition]]
key = "BSE_Closing"     #마감여부
value = "1"             #마감
value_type = "Integer"

[[V105-1.Sub]]
key = "BSE_VAT Category Code"
query = "SELECT [BSE_Category Code]
         FROM [#Company$B_VAT Category]
         WHERE [BSE_Non-VAT Total Report] = 1"