# V112 대손세액공제(변제)신고서
title = "VAT112"
[V112]
# 대손세액공제(변제)신고서의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String","true"],             #Main Key. << 모든 정의에 들어 있어야 함. 세번째 항목은 Key 값 유무.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

    ["REPAY_AMT_TOT","Number"],      #금액 합계
    ["REPAY_TAX_TOT","Number"],      #세액 합계
    ["D1_REPAY_AMT_TOT","Number"],   #대손금액 합계
    ["D1_REPAY_TAX_TOT","Number"],   #대손세액 합계
    ["D2_REPAY_AMT_TOT","Number"],   #변제금액 합계
    ["D2_REPAY_TAX_TOT","Number"],   #변제세액 합계
    ["REPAY_CD","String"],           #대손구분(D1:대손발생,D2:대손변제)
    ["SEQN","Number"],               #일련번호
    ["REPAY_DATE","String"],         #일자
    ["REPAY_AMT","Number"],          #금액
    ["DC_RATE","String"],            #공제율
    ["REPAY_TAX","Number"],          #세액
    ["RGST_NAME","String"],          #법인명(상호)
    ["REPRE_NAME","String"],         #성명(대표자명)
    ["RGST_NO","String"],            #등록번호(사업자번호 Or 주민번호)
    ["REMARK","String"],             #사유
    ["RGST_TYPE,"String"]            #등록번호 구분(C:사업자번호 Or P:주민등록번호)

]

# 화면상의 계산 식을 위한 공간 / 자동화 하기 위해 고민이 필요함.
calc = [
["TOTAL_AMOUNT","(CARD_TOTAL_AMOUNT+CASH_TOTAL_AMOUNT-XXX)/YYY*ZZZ"]
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V112 (대손세액공제(변제)신고서)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Pay_Bill CorpIndv Type",
"BSE_ETAX Complete issue",
"BSE_Editable Tot Total Amount",
"BSE_Editable Tot VAT Amount",
"BSE_VAT Registration No_",
"BSE_VAT Name"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V112.Condition]]
key = "BSE_VAT Type"
value = "1"
value_type = "Integer"

[[V112.Sub]]
key = "BSE_VAT Category Code"
query = "SELECT [BSE_Category Code]
         FROM [#Company$B_VAT Category]
         WHERE [BSE_VAT Total Report] = 1"