# V117 신용카드매출전표 등 발행금액집계표
title = "VAT117"
[V117]
# 신용카드매출전표 등 발행금액집계표의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String"],             #Main Key. << 모든 정의에 들어 있어야 함.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

    ["TOTAL_AMOUNT","Number"],       #전체발행금액 (계산값)
    ["CARD_TOTAL_AMOUNT","Number"],  #신용카드등발행금액_합계 (계산값)
    ["CASH_TOTAL_AMOUNT","Number"],  #현금영수증발행금액_합계 (계산값)

    ["TAX_TOTAL_AMOUNT","Number"],   #발행금액합계_과세매출분 (계산값)
    ["TAX_CARD_AMOUNT","Number"],    #신용카드등발행금액_과세매출분 (데이터베이스)
    ["TAX_CASH_AMOUNT","Number"],    #현금영수증발행금액_과세매출분 (데이터베이스)

    ["NOTAX_TOTAL_AMOUNT","Number"], #발행금액합계_면세매출분 (계산값)
    ["NOTAX_CARD_AMOUNT","Number"],  #신용카등등발행금액_면세매출분 (데이터베이스)
    ["NOTAX_CASH_AMOUNT","Number"],  #현금영수증발행금액_면세매출분 (데이터베이스)

    ["SVC_TOTAL_AMOUNT","Number"],   #발행금액합계_봉사료(사용자입력)
    ["SVC_CARD_AMOUNT","Number"],    #신용카등등발행금액_봉사료(사용자입력)
    ["SVC_CASH_AMOUNT","Number"],    #현금영수증발행금액_봉사료(사용자입력)

    ["TAX_BILL_AMOUNT","Number"],    #세금계산서교부금액(집계표) (사용자입력)
    ["BILL_AMOUNT","Number"]         #계산서교부금액(집계표) (사용자입력)
]

# 화면상의 계산 식을 위한 공간 / 자동화 하기 위해 고민이 필요함.
calc = [
["TOTAL_AMOUNT","(CARD_TOTAL_AMOUNT+CASH_TOTAL_AMOUNT-XXX)/YYY*ZZZ"]
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V164 (신용카드매출전표등 수령금액 합계표)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Editable Tot Total Amount"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V117.Condition]]
key = "BSE_VAT Type"
value = "1"
value_type = "Integer"

[[V117.Condition]]
key = "BSE_Closing"
value = "1"
value_type = "Integer"

#[[V117.Condition]]
#key = "BSE_VAT Category Code"
#value = ["S060","S070","S080","S090","S100","S110"]
#value_type = "String"