# V149 건물등감가상각자산취득명세서
title = "VAT149"
[V149]
# 건물등감가상각자산취득명세서의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String","true"],      #Main Key. << 모든 정의에 들어 있어야 함. 세번째 항목은 Key 값 유무.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

    ["TOT_COUNT","Number"],          #합계 건수
    ["TOT_AMOUNT","Number"],         #합계 공급가액
    ["TOT_TAX","Number"],            #합계 세액
    ["TOT_REMARK","String"],         #합계 비고

    ["BID_COUNT","Number"],          #건물.구축물 건수
    ["BID_AMOUNT","Number"],         #건물.구축물 공급가액
    ["BID_TAX","Number"],            #건물.구축물 세액
    ["BID_REMARK","String"],         #건물.구축물 비고

    ["MAC_COUNT","Number"],          #기계장치 건수
    ["MAC_AMOUNT","Number"],         #기계장치 공급가액
    ["MAC_TAX","Number"],            #기계장치 세액
    ["MAC_REMARK","String"],         #기계장치 비고

    ["CAR_COUNT","Number"],          #차량운반구 건수
    ["CAR_AMOUNT","Number"],         #차량운반구 공급가액
    ["CAR_TAX","Number"],            #차량운반구 세액
    ["CAR_REMARK","String"],         #차량운반구 비고

    ["ETC_COUNT","Number"],          #그밖의감가상각자산 건수
    ["ETC_AMOUNT","Number"],         #그밖의감가상각자산 공급가액
    ["ETC_TAX","Number"],            #그밖의감가상각자산 세액
    ["ETC_REMARK","String"]          #그밖의감가상각자산 비고
]

# 화면상의 계산 식을 위한 공간 / 자동화 하기 위해 고민이 필요함.

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V149 (건물등감가상각자산취득명세서)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Pay_Bill CorpIndv Type",
"BSE_ETAX Complete issue",
"BSE_Credit Card Number",
"BSE_Editable Tot Actual Amount",
"BSE_Editable Tot VAT Amount",
"BSE_VAT Registration No_",
"BSE_VAT Name"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V149.Condition]]
key = "BSE_VAT Type"
value = "0"
value_type = "Integer"

[[V149.Condition]]
key = "BSE_VAT Category Code"
value = [
"P051","P271","P281","P291","P301","P311","P321","P331","P341",
"P052","P272","P282","P292","P302","P312","P322","P332","P342",
"P053","P273","P283","P293","P303","P313","P323","P333","P343",
"P054","P274","P284","P294","P304","P314","P324","P334","P344"
]
value_type = "String"