# V177 영세율 매출 명세서
title = "VAT177"
[V177]
# 영세율 매출 명세서 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
    ["VATKEY","String","true"],             #Main Key. << 모든 정의에 들어 있어야 함. 세번째 항목은 Key 값 유무.
    ["COMPANY_CODE","String"],       #회사코드
    ["YEAR","String"],               #년도
    ["VATQT","String"],              #신고분기
    ["VATRPTTYPE","String"],         #신고타입

    ["a_a","Number"],  #직접수출(대행수출 포함)
    ["a_b","Number"],  #중계무역.위탁판매.외국인도 또는 위탁가공무역 방식의 수출
    ["a_c","Number"],  #내국신용장.구매확인서에 의하여 공급하는 재화
    ["a_d","Number"],  #한국국제협력단 및 한국국제보건의료재단에 공긍하는 해외반출용 재화
    ["a_e","Number"],  #수탁가공무역 수출용으로 공급하는 재화
    ["b_a","Number"],  #국외에서 제공하는 용역
    ["c_a","Number"],  #선박.항공기에 의한 외국항행용역
    ["c_b","Number"],  #국제복합운송계약에 의한 외국항행용역

    ["d_a","Number"],  #국내에서 비거주자.외국법인에게 공급되는 재화 또는 용역
    ["d_b","Number"],  #수출재화임가공용역
    ["d_c","Number"],  #외국항행 선박.항공기 등에 공급하는 재화 또는 용역
    ["d_d","Number"],  #국내 주재 외교공관, 영사기관, 국제연합과 이에 준하는 국제기구,
                       # 국제연합군 또는 미국군에게 공급하는 재화 또는 용역
    ["d_e","Number"],  #관광진흥법」 에 따른 일반여행업자 또는 외국인전용 관광기념품
                       # 판매업자가 외국인관광객에게 공급하는 관광알선용역 또는 관광기념품
    ["d_f","Number"],  #외국인전용판매장 또는 주한외국군인 등의 전용 유흥음식접에서
                       # 공급하는 재화 또는 용역
    ["d_g","Number"],  #외교관 등에게 공급하는 재화 또는 용역
    ["d_h","Number"],  #외국인환자 유치용역

    ["e_a","Number"],  #부가가치세법에 따른 영세율 적용 공급실적 합계 (계산값)

    ["f_a","Number"],  #방위산업물자 및 군부대 등에 공급하는 석유류
    ["f_b","Number"],  #도시철도건설용역
    ["f_c","Number"],  #국가.지방자치단체에 공급하는 사회기반시설 등
    ["f_d","Number"],  #장애인용 부장구 및 장애인용 정보통신기기 등
    ["f_e","Number"],  #농.어민 등에게 공급하는 농업용.축산업용.임업용 또는 어업용 기자재
    ["f_f","Number"],  #외국인관광객 등에게 공급하는 재화
    ["f_g","Number"],  #제주특별자치도 면세품판매장에서 판매하거나 제주특별자치도
                       # 면세품판매장에 공급하는 물품
    ["g_a","Number"],  #조세특례제한법 및 그 밖의 법률에 따른 영세율 적용 공급실적 합계 (계산값)
    ["h_a","Number"]  #영세율 적용 공급실적 총 합계 (11)+(12) (계산값)
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V177에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"BSE_VAT Category Code",
"BSE_Editable Tot Total Amount"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V177.Condition]]
key = "BSE_VAT Type"
value = "1"
value_type = "Integer"

[[V177.Condition]]
key = "BSE_Closing"
value = "1"
value_type = "Integer"

[[V177.Condition]]
key = "BSE_VAT Category Code"
value = ["S130"]
value_type = "String"

[[V177.Condition]]
key = "BSE_Document Name"
value = [4, 5]
value_type = "Integer"