# V164 신용카드매출전표등 수령금액 합계표
title = "VAT164"
[V164]
# 신용카드매출전표등 수령금액 합계표의 화면을 위한 테이블 정의
# 화면을 구성하게되는 입력폼이나 출력되는 대상을 정하는 것과 동일합니다.
schema = [
["COMPANY CODE","String"],
["YEAR","String"],
["DATA_TYPE","String"],
["FORM_CD","String"],
["CASH COUNT","Number"],
["CASH AMOUNT TOTAL","Number"],
["CASH TAX TOTAL","Number"],
["DRIVER COUNT","Number"],
["DRIVER AMOUNT TOTAL","Number"],
["DRIVER TAX TOTAL","Number"],
["BUSINESS CARD COUNT","Number"],
["BUSINESS CARD AMOUNT TOTAL","Number"],
["BUSINESS CARD TAX TOTAL","Number"],
["CARD COUNT","Number"],
["CARD AMOUNT TOTAL","Number"],
["CARD TAX TOTAL","Number"],
[
    ["CARD TYPE","String"],
    ["SEQN","String"],
    ["CARD NUMBER","String"],
    ["BUSINESS NO","String"],
    ["BUSINESS NAME","String"],
    ["SUPPLY AMOUNT","Number"],
    ["TAX AMOUNT","Number"],
    ["MISSED","String"],
    ["CATEGORY CODE","String"],
    ["CATEGORY Name","String"],
    ["Status","String"],
    ["CNT","String"],
    ["FA Type","String"]
]
,
["Status","String"],
["VAT Missing","String"],
["Start DATE","Date"],
["End DATE","Date"],
["FA CASH COUNT","Number"],
["FA CASH AMOUNT TOTAL","Number"],
["FA CASH TAX TOTAL","Number"],
["FA DRIVER COUNT","Number"],
["FA DRIVER AMOUNT TOTAL","Number"],
["FA DRIVER TAX TOTAL","Number"],
["FA BUSINESS CARD COUNT","Number"],
["FA BUSINESS CARD AMOUNT TOTAL","Number"],
["FA BUSINESS CARD TAX TOTAL","Number"],
["FA CARD COUNT","Number"],
["FA CARD AMOUNT TOTAL","Number"],
["FA CARD TAX TOTAL","Number"]
]

# MSSQL의 NAV Table DocumentVATEntry 에서 가져올 대상을 지정합니다. (SQL 컬럼명을 지정합니다.)
# V164 (신용카드매출전표등 수령금액 합계표)에서 사용 할 MSSQL 컬럼명을 입력합니다.
Entries = [
"Document VAT No_",
"Document VAT Type",
"Posting Type",
"VAT Type",
"VAT No_",
"VAT Name",
"VAT Date",
"VAT Category Group",
"VAT Category Group Name",
"VAT Category",
"VAT Category Name",
"VAT Sub",
"VAT Sub Category",
"VAT Sub Category Name",
"Buyer Issued",
"VAT Missing",
"Special Excise Rate"
]

# NAV 쿼리를위한 조건을 입력합니다.
[[V164.Condition]]
key = "VAT Type"
value = "0"
value_type = "Integer"

[[V164.Condition]]
key = "Closing"
value = "1"
value_type = "Integer"

[[V164.Condition]]
key = "VAT Category Group"
value = ["I","J","K"]
value_type = "String"